spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heulgkkom?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&connectTimeout=5000&socketTimeout=10000&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
server:
  port: 8079
